markdown: rdiscount
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "something said here"
markdown: rdiscount

author: "yulin"
atom-baseurl: "http://yulin.me"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: https://www.flickr.com/photos/snake_bill/
