highlighter: rouge
markdown: kramdown
permalink: /:year/:month/:day/:title.html
name: "六月烟雨"

author: "Yulin"
atom-baseurl: "https://yulin.me"

disqus: "yulin-me"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: https://www.instagram.com/snake_bill/
