highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "something said here"
markdown: kramdown

author: "Yulin"
atom-baseurl: "http://yulin.me"

disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: yulin-me

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: https://www.flickr.com/photos/snake_bill/
